//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18063
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAccount.Service.SecondService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://schemas.datacontract.org/2004/07/MyAccount.Service.SecondService")]
    public partial class UserInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<bool> AdvertisingOptInField;
        
        private string CountryIsoCodeField;
        
        private System.DateTime DateModifiedField;
        
        private string LocaleField;
        
        private System.Guid UserIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> AdvertisingOptIn
        {
            get
            {
                return this.AdvertisingOptInField;
            }
            set
            {
                this.AdvertisingOptInField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryIsoCode
        {
            get
            {
                return this.CountryIsoCodeField;
            }
            set
            {
                this.CountryIsoCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateModified
        {
            get
            {
                return this.DateModifiedField;
            }
            set
            {
                this.DateModifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Locale
        {
            get
            {
                return this.LocaleField;
            }
            set
            {
                this.LocaleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserNotFound", Namespace="http://schemas.datacontract.org/2004/07/MyAccount.Service.SecondService")]
    public partial class UserNotFound : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CustomErrorField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomError
        {
            get
            {
                return this.CustomErrorField;
            }
            set
            {
                this.CustomErrorField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IUserInfoProvider")]
public interface IUserInfoProvider
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserInfoProvider/GetUserInfo", ReplyAction="http://tempuri.org/IUserInfoProvider/GetUserInfoResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(MyAccount.Service.SecondService.UserNotFound), Action="http://tempuri.org/IUserInfoProvider/GetUserInfoUserNotFoundFault", Name="UserNotFound", Namespace="http://schemas.datacontract.org/2004/07/MyAccount.Service.SecondService")]
    MyAccount.Service.SecondService.UserInfo GetUserInfo(System.Guid userId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserInfoProvider/GetUserInfo", ReplyAction="http://tempuri.org/IUserInfoProvider/GetUserInfoResponse")]
    System.Threading.Tasks.Task<MyAccount.Service.SecondService.UserInfo> GetUserInfoAsync(System.Guid userId);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IUserInfoProviderChannel : IUserInfoProvider, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class UserInfoProviderClient : System.ServiceModel.ClientBase<IUserInfoProvider>, IUserInfoProvider
{
    
    public UserInfoProviderClient()
    {
    }
    
    public UserInfoProviderClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public UserInfoProviderClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UserInfoProviderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UserInfoProviderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public MyAccount.Service.SecondService.UserInfo GetUserInfo(System.Guid userId)
    {
        return base.Channel.GetUserInfo(userId);
    }
    
    public System.Threading.Tasks.Task<MyAccount.Service.SecondService.UserInfo> GetUserInfoAsync(System.Guid userId)
    {
        return base.Channel.GetUserInfoAsync(userId);
    }
}
